#!/usr/bin/env bash

PACKAGE_ID="HelloWorld"
mkdir -p "$(pwd)/packages/${PACKAGE_ID}"
ARTIFACTS_DIR="$(pwd)/packages/${PACKAGE_ID}"
DRAFT_HANDLING="SKIP"


./auto/flashpipe sync --config ./flashpipe.yaml --package-id "${PACKAGE_ID}" --draft-handling "${DRAFT_HANDLING}" --dir-git-repo "$(pwd)/" --dir-artifacts "${ARTIFACTS_DIR}" --target git --debug --sync-package-details
