# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: pipeline
on:
  workflow_dispatch:
  push:

jobs:
# Unit test
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: 'Local unit test with Maven'
        #run: mvn clean test
        run: |
          echo "It's all green! well done"

# Update designtime
  upload:
    runs-on: ubuntu-latest
    needs: tests
    container:
      image: engswee/flashpipe:latest
    steps:
      - uses: actions/checkout@v4

      - name: 'Upload ALL THINGS in HelloWorld'
        uses: engswee/flashpipe-action/update/artifact@v1
        with:
          tmn-host: f69313cftrial.it-cpitrial03.cfapps.ap21.hana.ondemand.com
          oauth-host: f69313cftrial.authentication.ap21.hana.ondemand.com
          oauth-clientid: ${{ secrets.DEV_CLIENT_ID }}
          oauth-clientsecret: ${{ secrets.DEV_CLIENT_SECRET }}
          dir-artifact-relative: artifacts/HelloWorld/
          package-id: HelloWorld

  # Deploy to runtime
  deploy:
    runs-on: ubuntu-latest
    needs: upload
    container:
      image: engswee/flashpipe:latest
    steps:
      - uses: actions/checkout@v4

      - name: 'Deploy the main IntegrationFlow in HelloWorld'
        uses: engswee/flashpipe-action/deploy@v1
        with:
          tmn-host: f69313cftrial.it-cpitrial03.cfapps.ap21.hana.ondemand.com
          oauth-host: f69313cftrial.authentication.ap21.hana.ondemand.com
          oauth-clientid: ${{ secrets.DEV_CLIENT_ID }}
          oauth-clientsecret: ${{ secrets.DEV_CLIENT_SECRET }}
          dir-artifact-relative: artifacts/HelloWorld/
          package-id: HelloWorld
          artifact-ids: HelloWorld.TestintegrationFlow
