# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: pipeline
on:
  workflow_dispatch:
  push:

jobs:
# Unit test
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: 'Run tests with Gradle'
        run: |
          cd packages/HelloWorld/Main/

          ./gradlew clean test

# Update designtime
  upload:
    runs-on: ubuntu-latest
    needs: tests
    container:
      image: engswee/flashpipe:latest
    steps:
      - uses: actions/checkout@v4

      - name: 'Upload all of HelloWorld using sync'
        uses: engswee/flashpipe-action/sync@v1
        with:
          tmn-host: f69313cftrial.it-cpitrial03.cfapps.ap21.hana.ondemand.com
          oauth-host: f69313cftrial.authentication.ap21.hana.ondemand.com
          oauth-clientid: ${{ secrets.DEV_CLIENT_ID }}
          oauth-clientsecret: ${{ secrets.DEV_CLIENT_SECRET }}
          target: tenant
          dir-artifacts-relative: packages/HelloWorld/
          package-id: HelloWorld

      - name: 'Bump package version'
        run: |
          apt-get update
          apt-get install -y jq

          cd packages/HelloWorld/

          VERSION="$(cat HelloWorld.json | jq -r .d.Version)"
          MAJOR_MINOR="$(echo $VERSION | cut -d'.' -f1,2)"
          NEW_VERSION="${MAJOR_MINOR}.${{ github.run_number }}"

          cat HelloWorld.json | jq ".d.Version = \"$NEW_VERSION\"" > package.json

          cat package.json

      - name: Update the package metadata
        uses: engswee/flashpipe-action/update/package@v1
        with:
          tmn-host: f69313cftrial.it-cpitrial03.cfapps.ap21.hana.ondemand.com
          oauth-host: f69313cftrial.authentication.ap21.hana.ondemand.com
          oauth-clientid: ${{ secrets.DEV_CLIENT_ID }}
          oauth-clientsecret: ${{ secrets.DEV_CLIENT_SECRET }}
          package-file-relative: packages/HelloWorld/package.json

  # Deploy to runtime
  deploy:
    runs-on: ubuntu-latest
    needs: upload
    container:
      image: engswee/flashpipe:latest
    steps:
      - uses: actions/checkout@v4

      - name: 'Deploy the main IntegrationFlow in HelloWorld'
        uses: engswee/flashpipe-action/deploy@v1
        with:
          tmn-host: f69313cftrial.it-cpitrial03.cfapps.ap21.hana.ondemand.com
          oauth-host: f69313cftrial.authentication.ap21.hana.ondemand.com
          oauth-clientid: ${{ secrets.DEV_CLIENT_ID }}
          oauth-clientsecret: ${{ secrets.DEV_CLIENT_SECRET }}
          artifact-ids: Main
